### ISSUE TITLE
The mouse wheel cannot be used in the left column of openwrt

### ISSUE THREAD

**Issue by 1WuNeiGui** [derisamedia/luci-theme-alpha#11]
Hello, your theme is beautiful. I cloned your source code and compiled it on my device (aarch64_cortex-a53), but I found that I can't use the mouse wheel in the left column of openwrt

**Comment by derisamedia** [comment]
oou, next time we fix it, thanks for loving my theme

**Comment by derisamedia** [comment]
check releases, we fix it, thanks for report the issue

**Comment by animegasan** [comment]
If this issue is resolved, it's better to just close it.
CC @derisamedia @1WuNeiGui
