### ISSUE TITLE
编译的时候找不到这个主题

### ISSUE THREAD

**Issue by xuexijiaoben** [derisamedia/luci-theme-alpha#12]
通过命令 git clone https://github.com/derisamedia/luci-theme-alpha.git feeds/luci/themes/luci-theme-alpha 下载，确认文件夹已经下载完成

./scripts/feeds update -a
./scripts/feeds install -a

make menuconfig 后在 luck-theme里没有找到luci-theme-alpha，试了几次都没有

**Comment by derisamedia** [comment]
ok, we will fix it, because we are in the process of improving it to the next version, thank you for the report, greetings (derisamedia from Indonesia, nice to meet you)

**Comment by bauw2008** [comment]
如果是官方openwrt-main分支，alpha主题源码makefilep修改
define Package/luci-theme-$(THEME_NAME)
  SECTION:=luci
  CATEGORY:=LuCI
- SUBMENU:=9. Themes
+SUBMENU:=4. Themes
  DEPENDS:=+libc
- TITLE:=LuCi Theme For OpenWrt And Alpha OS ONLY - $(THEME_TITLE)
+TITLE:=Tema LuCi - $(THEME_TITLE)   这样测试是正常的。
另外最新的3.9b版本，会错误显示2个主题菜单选项也可以这个修改来解决。

**Comment by derisamedia** [comment]
ok, because when I compile there is no problem (using OpenWrt SDK 22.xx) but some people have problems, I will update it.
the sub theme is in menu 9. themes because I deliberately put it there because there was a problem. thanks for reporting, I will fix it in the next update. greetings from indonesia 😊

**Comment by 1WuNeiGui** [comment]
我刚才也把源码拉进去编译了一下看了看，他在原项目里的luci-theme里没有，但是他新建了一个另外的luci-theme，而这个alpha主题在另外的这个luci-theme里
![屏幕截图 2024-01-07 211301](https://github.com/derisamedia/luci-theme-alpha/assets/95472175/e2a7ceeb-efc6-4f8b-a317-20d90ca19deb)
如下图，有4和9两个theme，4里面找不到alpha，而在9里面可以找到alpha主题

**Comment by derisamedia** [comment]
因为为了便于查找，我建议在图像 (*) 之前选择它，这样在编译时它就会成为优先事项。

**Comment by CHUNGSEV** [comment]
我按照你所说的修改了它，但是当我运行 ./scripts/feeds update -a 时，我仍然收到此错误：
创建索引文件'./feeds/luci_theme_alpha.index'
grep: feeds/luci_theme_alpha/Makefile:$(eval: 没有这样的文件或目录
grep: $(call: 没有这样的文件或目录
grep: B​​uildPackage,luci-theme-$(THEME_NAME)))/Makefile: 没有这样的文件或目录
/workspaces/codespaces-jupyter/openwrt/feeds/luci_theme_alpha.tmp/info/.files-packageinfo.mk:1: *** 目标模式不包含“%”。 停止。

**Comment by xuexijiaoben** [comment]
I see,
I found the theme in menu 9,
thank you, it's very beautiful

**Comment by derisamedia** [comment]
> I see, I found the theme in menu 9, thank you, it's very beautiful

thanks bro

**Comment by animegasan** [comment]
If this issue is resolved, it's better to just close it.

CC @derisamedia @xuexijiaoben
