### ISSUE TITLE
Status Overview

### ISSUE THREAD

**Issue by RegaAG** [derisamedia/luci-theme-alpha#16]
ReferenceError

![Screenshot 2024-02-06 125211](https://github.com/derisamedia/luci-theme-alpha/assets/113965184/fc22b6e4-1774-4994-bcc6-63d525c58347)

**Comment by animegasan** [comment]
> ReferenceError
> 
> ![Screenshot 2024-02-06 125211](https://private-user-images.githubusercontent.com/113965184/302516469-fc22b6e4-1774-4994-bcc6-63d525c58347.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMTQ2MjksIm5iZiI6MTcwNzIxNDMyOSwicGF0aCI6Ii8xMTM5NjUxODQvMzAyNTE2NDY5LWZjMjJiNmU0LTE3NzQtNDk5NC1iY2M2LTYzZDUyNWM1ODM0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxMDEyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzc5YjQ2ZDJhZTNhMTJhZGEyNjA4MjQ1NzBiNTgxMjhlOGM0YjhmZDc0OWM1MmYxYzU2MDU0MWEzODNiMTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UmjcWSR9aR40EIAr2T2cq2QSE_DI2tpqBZt_-uazBss)

Ini bukan error dari themesnya. Tetapi JavaScript anda yang error. Jadi lebih baik untuk menyelesaikan issue ini. Thanks
