### ISSUE TITLE
Bugs pada style.css

### ISSUE THREAD

**Issue by animegasan** [derisamedia/luci-theme-alpha#18]
# Bugs pada file `style/style.css `

![image](https://github.com/derisamedia/luci-theme-alpha/assets/14136053/5ea36a09-bf0a-4454-bf64-5807c13188e0)

Pada file tersebut ada tanda ^M. Mungkin bisa di fix pada update selanjutnya.

Referensi 
[Remove ^M](https://stackoverflow.com/questions/19406418/remove-m-characters-from-file-using-sed)

**Comment by derisamedia** [comment]
kok bisa ya 😅

Pada Rab, 7 Feb 2024 12.12, Hilman Maulana ***@***.***>
menulis:

**Comment by animegasan** [comment]
> kok bisa ya 😅
Kalau paje VSC, Emang bugs di Visual Studio Code.

**Comment by derisamedia** [comment]
iya ya, keenakan pake vscode sih 😂😂

Pada Rab, 7 Feb 2024 12.20, Hilman Maulana ***@***.***>
menulis:

**Comment by animegasan** [comment]
> iya ya, keenakan pake vscode sih 😂😂 Pada Rab, 7 Feb 2024 12.20, Hilman Maulana ***@***.***> menulis:

Nanti saya closed issue pad udah fix yo

**Comment by animegasan** [comment]
Closed by #20
