### ISSUE TITLE
Mengubah metode background dari CSS ke htm?

### ISSUE THREAD

**Issue by animegasan** [derisamedia/luci-theme-alpha#19]
Saya mengutip dari argon theme pada

https://github.com/jerrykuku/luci-theme-argon/blob/ed263b0add5ff4320f4dd1c55933794c11ef6294/luasrc/view/themes/argon/sysauth.htm#L125

> Login Background
> https://github.com/derisamedia/luci-theme-alpha/blob/6b39b599e1bfadb7d849f1c637b86ac5cd74cbe7/template/sysauth.htm#L23

> Dashboard Background
> https://github.com/derisamedia/luci-theme-alpha/blob/6b39b599e1bfadb7d849f1c637b86ac5cd74cbe7/template/header.htm#L60

Bagaimana jika kita mengukuti kode mereka?

**Comment by derisamedia** [comment]
boleh , berikan yang terbaik untuk tema kami

Pada Kam, 8 Feb 2024 13.14, Hilman Maulana ***@***.***>
menulis:

**Comment by animegasan** [comment]
Closed by #20
