### ISSUE TITLE
Todo:

### ISSUE THREAD

**Issue by AmirulAndalib** [derisamedia/luci-theme-alpha#9]
hi thank you for this awesome project, however there are some bugs:

![image](https://github.com/derisamedia/luci-theme-alpha/assets/86344856/a4523439-a595-4626-b8f1-7702626058a2)

luci kmod dashboard doesnt match with background, needs fix and scrollbar on left is missing, it would be awesome if you develop a seperate bg manager like luci theme argon: 

https://github.com/jerrykuku/luci-theme-argon

**Comment by derisamedia** [comment]
because the luci-app-dashboard css is different / has not entered the luci-theme-alpha css, it cannot be set or does not adjust to the theme. later it will be fixed by us. thank you for your support.

**Comment by animegasan** [comment]
If this issue is resolved, it's better to just close it.

CC @derisamedia @AmirulAndalib
